/** 1월 — 31일 (새해·고요) */
export const MONTH_1_SEEDS = [
  { month: 1, day: 1, text: "기억에 남는 하루에 대해 이야기해주세요", tags: ["memory"] },
  { month: 1, day: 2, text: "버킷리스트 중 이뤘던 것 가운데 기억에 남는 것에 대해 이야기해주세요", tags: ["goal","experience"] },
  { month: 1, day: 3, text: "당신의 가치관이 바뀌게 된 사건에 대해 이야기해주세요", tags: ["growth","reflection"] },
  { month: 1, day: 4, text: "당신은 지금 행복한가요? 지금의 마음을 이야기해주세요", tags: ["emotion"] },
  { month: 1, day: 5, text: "올해의 목표에 대해 이야기해주세요", tags: ["goal"] },
  { month: 1, day: 6, text: "목표를 이뤄서 기억에 남는 순간에 대해 이야기해주세요", tags: ["goal","experience"] },
  { month: 1, day: 7, text: "올해 꼭 해보고 싶은 일에 대해 이야기해주세요", tags: ["goal"] },
  { month: 1, day: 8, text: "누군가에게 위로받았던 순간에 대해 이야기해주세요", tags: ["relationship","hope"] },
  { month: 1, day: 9, text: "오랜 친구와의 추억에 대해 이야기해주세요", tags: ["relationship","memory"] },
  { month: 1, day: 10, text: "낯선 사람에게 친절을 받았던 기억에 대해 이야기해주세요", tags: ["relationship","experience"] },
  { month: 1, day: 11, text: "특정 장소와 연결된 기억에 대해 이야기해주세요", tags: ["memory","place"] },
  { month: 1, day: 12, text: "특정 향기와 연결된 기억에 대해 이야기해주세요", tags: ["memory","scent"] },
  { month: 1, day: 13, text: "특정 음식과 연결된 기억에 대해 이야기해주세요", tags: ["memory","food"] },
  { month: 1, day: 14, text: "눈 오는 날의 기억에 대해 이야기해주세요", tags: ["memory","weather"] },
  { month: 1, day: 15, text: "친구들은 당신을 어떤 사람이라고 말하나요? 그 말을 떠올려 이야기해주세요", tags: ["relationship","self"] },
  { month: 1, day: 16, text: "당신이 좋아하는 사람들의 특징은 어떤 게 있는지 이야기해주세요", tags: ["relationship"] },
  { month: 1, day: 17, text: "지금 고마운 사람 한 명을 떠올릴 수 있나요? 왜 고마운지 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 1, day: 18, text: "사랑하거나 좋아하는 사람에게 하고 싶은 말이 있나요? 그 마음을 이야기해주세요", tags: ["relationship","emotion"] },
  { month: 1, day: 19, text: "최근에 웃었던 기억에 대해 이야기해주세요", tags: ["emotion","experience"] },
  { month: 1, day: 20, text: "혼자 있을 때의 나와 다른 사람 앞의 나, 어떤 차이가 있나요? 그 차이를 이야기해주세요", tags: ["self","emotion"] },
  { month: 1, day: 21, text: "사람들 사이에서도 외로웠던 기억에 대해 이야기해주세요", tags: ["emotion","memory"] },
  { month: 1, day: 22, text: "책이나 사람에게서 받은 기억에 남는 조언이 있나요? 그 조언을 이야기해주세요", tags: ["growth","experience"] },
  { month: 1, day: 23, text: "다시 시작하고 싶은 것이 있나요? 왜 그런지 이야기해주세요", tags: ["hope","growth"] },
  { month: 1, day: 24, text: "요즘 하루는 보통 어떻게 흘러가나요? 요즘의 루틴을 이야기해주세요", tags: ["daily"] },
  { month: 1, day: 25, text: "당신의 하루를 한 문장으로 표현한다면 무엇인가요? 그 문장을 고른 이유를 이야기해주세요", tags: ["daily","reflection"] },
  { month: 1, day: 26, text: "오늘 하루를 한 단어로 표현한다면 무엇인가요? 그 단어를 고른 이유를 이야기해주세요", tags: ["daily","emotion"] },
  { month: 1, day: 27, text: "최근에 어떤 도전을 했는지 이야기해주세요", tags: ["growth","experience"] },
  { month: 1, day: 28, text: "요즘 배우고 있는 것에 대해 이야기해주세요", tags: ["growth"] },
  { month: 1, day: 29, text: "후회했지만 그 덕분에 성장했다고 느낀 경험이 있나요? 그 순간을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 1, day: 30, text: "용기를 내야 했던 순간이 있었나요? 그때의 순간을 이야기해주세요", tags: ["growth","experience"] },
  { month: 1, day: 31, text: "누군가에게 용기를 받았던 적이 있나요? 그때의 순간을 이야기해주세요", tags: ["hope","relationship"] },
] as const;
