/** 1월 — 31일 (겨울·새해·고요) */
export const MONTH_1_SEEDS = [
  { month: 1, day: 1, text: "새해 첫날, 올해의 나에게 바라는 한 가지는?" },
  { month: 1, day: 2, text: "지난해를 떠올리며 고마웠던 순간은?" },
  { month: 1, day: 3, text: "겨울 햇살 아래 잠시 멈춘 이유는?" },
  { month: 1, day: 4, text: "요즘 마음을 무겁게 한 것과 가볍게 한 것은?" },
  { month: 1, day: 5, text: "따뜻한 차 한 잔과 함께 떠오른 생각은?" },
  { month: 1, day: 6, text: "작은 다짐 하나, 오늘부터 지켜볼 것은?" },
  { month: 1, day: 7, text: "혼자 있는 시간이 나에게 준 선물은?" },
  { month: 1, day: 8, text: "바깥 풍경을 보며 느낀 평온함이 있었나요?" },
  { month: 1, day: 9, text: "아직 말하지 못한 고마움이 떠오르나요?" },
  { month: 1, day: 10, text: "오늘 몸과 마음에 가장 필요했던 것은?" },
  { month: 1, day: 11, text: "어릴 적 겨울 기억이 문득 떠오른다면?" },
  { month: 1, day: 12, text: "지금의 나를 지지해 주는 사람은 누구인가요?" },
  { month: 1, day: 13, text: "천천히 걸으며 들은 소리나 말은?" },
  { month: 1, day: 14, text: "올해 꼭 해보고 싶은 작은 모험은?" },
  { month: 1, day: 15, text: "밤하늘을 보며 생각한 것이 있다면?" },
  { month: 1, day: 16, text: "나를 웃게 해준 의외의 순간은?" },
  { month: 1, day: 17, text: "조용한 방 안, 창가에 앉아 느낀 감정은?" },
  { month: 1, day: 18, text: "요즘 마음에 남는 노래나 문장은?" },
  { month: 1, day: 19, text: "스스로에게 용서하고 싶은 일이 있나요?" },
  { month: 1, day: 20, text: "누군가의 따뜻한 말이 기억난다면?" },
  { month: 1, day: 21, text: "겨울 냄새가 불러온 추억은 무엇인가요?" },
  { month: 1, day: 22, text: "지금 이 순간, 가장 소중한 것은?" },
  { month: 1, day: 23, text: "내일의 나에게 건네고 싶은 응원은?" },
  { month: 1, day: 24, text: "손이 시릴 때 그리게 되는 사람이나 장소는?" },
  { month: 1, day: 25, text: "오늘 나를 한 걸음 나아가게 한 것은?" },
  { month: 1, day: 26, text: "불빛 아래 나눈 대화가 떠오르나요?" },
  { month: 1, day: 27, text: "겨울밤, 마음이 가장 편해지는 시간은?" },
  { month: 1, day: 28, text: "지나간 하루 중 다시 살고 싶은 순간은?" },
  { month: 1, day: 29, text: "나를 지금의 나로 만든 작은 선택은?" },
  { month: 1, day: 30, text: "창밖의 계절을 보며 느낀 바람은?" },
  { month: 1, day: 31, text: "한 달의 끝, 마음에 남는 색깔은?" },
] as const;
