/** 2월 — 28일 (겨울 끝·관계·따뜻함) */
export const MONTH_2_SEEDS = [
  { month: 2, day: 1, text: "짧은 겨울 날, 마음을 녹여준 것은?" },
  { month: 2, day: 2, text: "연락하고 싶었던 사람이 떠오르나요?" },
  { month: 2, day: 3, text: "요즘 나를 붙잡아 주는 작은 습관은?" },
  { month: 2, day: 4, text: "바람 소리를 들으며 떠올린 장면은?" },
  { month: 2, day: 5, text: "스스로를 다정하게 대한 순간이 있었나요?" },
  { month: 2, day: 6, text: "아직 꺼내지 못한 이야기가 있나요?" },
  { month: 2, day: 7, text: "눈이나 비 온 날, 창밖을 보며 생각한 것은?" },
  { month: 2, day: 8, text: "내일을 기대하게 만든 작은 신호는?" },
  { month: 2, day: 9, text: "지금의 관계에서 고마운 점은?" },
  { month: 2, day: 10, text: "몸이 보내는 피로, 어떻게 돌봤나요?" },
  { month: 2, day: 11, text: "어제의 나에게 해주고 싶은 말은?" },
  { month: 2, day: 12, text: "따뜻한 음식이 전해준 위로가 있었나요?" },
  { month: 2, day: 13, text: "혼자여도 괜찮다고 느낀 때는?" },
  { month: 2, day: 14, text: "사랑한다는 말 없이도 전해진 마음은?" },
  { month: 2, day: 15, text: "봄이 오기 전, 마음속에 싹 트는 것은?" },
  { month: 2, day: 16, text: "최근 나를 울컥하게 한 감동은?" },
  { month: 2, day: 17, text: "잊고 있던 좋은 기억이 돌아왔다면?" },
  { month: 2, day: 18, text: "오늘 나를 지켜준 경계나 선택은?" },
  { month: 2, day: 19, text: "밤에 잠들기 전, 머릿속에 남은 것은?" },
  { month: 2, day: 20, text: "누군가의 손길이 기억나는 순간은?" },
  { month: 2, day: 21, text: "지금 가장 그리운 계절이나 장소는?" },
  { month: 2, day: 22, text: "나를 있는 그대로 받아준 사람은?" },
  { month: 2, day: 23, text: "차분해지기 위해 했던 일은?" },
  { month: 2, day: 24, text: "미래의 나에게 묻고 싶은 질문은?" },
  { month: 2, day: 25, text: "오늘 하루, 마음의 온도는 몇 도였나요?" },
  { month: 2, day: 26, text: "작은 선물이나 말이 기억에 남는다면?" },
  { month: 2, day: 27, text: "겨울 끝자락, 놓아주고 싶은 것은?" },
  { month: 2, day: 28, text: "이번 달을 한 문장으로 남긴다면?" },
] as const;
