/** 2월 — 28일 (겨울) */
export const MONTH_2_SEEDS = [
  { month: 2, day: 1, text: "요즘 머릿속에서 가장 많이 했던 생각은 무엇인가요? 그 생각을 이야기해주세요", tags: ["emotion","daily"] },
  { month: 2, day: 2, text: "최근에 행복했던 순간이 있었나요? 그때의 순간을 이야기해주세요", tags: ["emotion","experience"] },
  { month: 2, day: 3, text: "좋아하는 계절이 있나요? 그 계절과 연결된 기억을 이야기해주세요", tags: ["memory","weather"] },
  { month: 2, day: 4, text: "생각만 해도 행복해지는 것은 어떤 게 있나요? 그것을 이야기해주세요", tags: ["emotion","hope"] },
  { month: 2, day: 5, text: "휴식이 되는 것은 어떤 게 있나요? 그것이 왜 쉬게 하는지 이야기해주세요", tags: ["daily","hope"] },
  { month: 2, day: 6, text: "당신이 진심으로 좋아하는 것은 무엇인가요? 그것을 이야기해주세요", tags: ["emotion","self"] },
  { month: 2, day: 7, text: "결국 해냈던 이야기를 해주세요", tags: ["growth","experience"] },
  { month: 2, day: 8, text: "조용한 밤에 함께 걸었던 사람이 떠오르나요? 그 순간을 이야기해주세요", tags: ["relationship","memory","weather"] },
  { month: 2, day: 9, text: "멀어졌지만 여전히 마음에 남는 사람이 있나요? 그 마음을 이야기해주세요", tags: ["hope","relationship"] },
  { month: 2, day: 10, text: "차가운 바깥공기 뒤 마음이 풀리던 순간이 있나요? 그때의 기억을 이야기해주세요", tags: ["memory","weather"] },
  { month: 2, day: 11, text: "가족에게 받았던 따뜻한 말이 떠오르나요? 그 말을 이야기해주세요", tags: ["relationship"] },
  { month: 2, day: 12, text: "지금 품고 있는 작은 기대가 있나요? 그 기대를 이야기해주세요", tags: ["hope","self"] },
  { month: 2, day: 13, text: "오래 연락하지 않았지만 생각나는 사람이 있나요? 그 사람과의 기억을 이야기해주세요", tags: ["relationship","memory"] },
  { month: 2, day: 14, text: "창밖 풍경이 오래 기억에 남는 순간이 있나요? 그 풍경을 이야기해주세요", tags: ["weather","memory"] },
  { month: 2, day: 15, text: "조용히 곁을 지켜준 사람이 있었나요? 그 순간을 이야기해주세요", tags: ["relationship","gratitude"] },
  { month: 2, day: 16, text: "기다림이 의미 있었던 적이 있나요? 그때의 마음을 이야기해주세요", tags: ["hope","reflection"] },
  { month: 2, day: 17, text: "처음 만났을 때의 인상이 아직도 남아 있나요? 그 순간을 이야기해주세요", tags: ["relationship","experience"] },
  { month: 2, day: 18, text: "공기와 함께 기억나는 향이 있나요? 그 향과 연결된 기억을 이야기해주세요", tags: ["memory","scent"] },
  { month: 2, day: 19, text: "마음을 편하게 해준 대화가 있었나요? 그 대화를 이야기해주세요", tags: ["relationship","emotion"] },
  { month: 2, day: 20, text: "조금씩 다가오고 있다고 느끼는 것이 있나요? 그것을 이야기해주세요", tags: ["hope","future"] },
  { month: 2, day: 21, text: "함께 웃었던 하루를 떠올릴 수 있나요? 그 하루를 이야기해주세요", tags: ["relationship","memory"] },
  { month: 2, day: 22, text: "따뜻한 실내로 들어섰던 순간이 기억나나요? 그 장소와 순간을 이야기해주세요", tags: ["weather","place"] },
  { month: 2, day: 23, text: "다시 안부를 전하고 싶은 사람이 있나요? 그 마음을 이야기해주세요", tags: ["relationship","hope"] },
  { month: 2, day: 24, text: "조용히 위로받았던 날이 있나요? 그 날을 이야기해주세요", tags: ["memory","emotion"] },
  { month: 2, day: 25, text: "누군가에게서 배운 나만의 방식이 있나요? 그것을 이야기해주세요", tags: ["relationship","self"] },
  { month: 2, day: 26, text: "어려운 시간을 지나온 기억이 있나요? 그때의 순간을 이야기해주세요", tags: ["hope","experience"] },
  { month: 2, day: 27, text: "함께 나눴던 따뜻한 음식이 떠오르나요? 그 기억을 이야기해주세요", tags: ["relationship","food"] },
  { month: 2, day: 28, text: "새롭게 시작하고 싶은 마음이 들었던 적이 있나요? 그 마음을 이야기해주세요", tags: ["memory","hope"] },
] as const;
