/** 3월 — 31일 (봄 시작·새싹·기대) */
export const MONTH_3_SEEDS = [
  { month: 3, day: 1, text: "봄기운이 느껴진 순간, 어디였나요?" },
  { month: 3, day: 2, text: "새로운 시작을 떠올리게 한 일은?" },
  { month: 3, day: 3, text: "햇살 아래 걸으며 생각한 것은?" },
  { month: 3, day: 4, text: "지난 겨울에서 가져온 배움은?" },
  { month: 3, day: 5, text: "꽃이나 새싹을 보며 느낀 설렘은?" },
  { month: 3, day: 6, text: "오늘 마음이 가벼워진 이유는?" },
  { month: 3, day: 7, text: "바뀌고 싶은 하루의 루틴이 있다면?" },
  { month: 3, day: 8, text: "누군가와 나누고 싶은 봄날의 풍경은?" },
  { month: 3, day: 9, text: "어린 시절 봄날이 떠오른다면?" },
  { month: 3, day: 10, text: "지금 꽃피우고 싶은 꿈은?" },
  { month: 3, day: 11, text: "창문을 열었을 때 들린 소리는?" },
  { month: 3, day: 12, text: "나를 성장시킨 최근의 경험은?" },
  { month: 3, day: 13, text: "봄비 뒤 맑아진 하늘을 보며 느낀 것은?" },
  { month: 3, day: 14, text: "사랑하는 사람에게 전하고 싶은 말은?" },
  { month: 3, day: 15, text: "오늘 나를 편안하게 해준 장소는?" },
  { month: 3, day: 16, text: "지나간 선택이 지금의 나에게 준 것은?" },
  { month: 3, day: 17, text: "따뜻해지는 날씨, 몸이 느끼는 변화는?" },
  { month: 3, day: 18, text: "최근 읽거나 본 것 중 마음에 남은 것은?" },
  { month: 3, day: 19, text: "작은 용기가 필요했던 순간은?" },
  { month: 3, day: 20, text: "봄날 산책길에서 본 풍경은?" },
  { month: 3, day: 21, text: "내일을 기다리게 만든 작은 약속은?" },
  { month: 3, day: 22, text: "나를 웃음 짓게 한 우연이 있었나요?" },
  { month: 3, day: 23, text: "지금 가장 아끼고 싶은 관계는?" },
  { month: 3, day: 24, text: "봄꽃 향기가 불러온 기억은?" },
  { month: 3, day: 25, text: "스스로에게 칭찬해 주고 싶은 일은?" },
  { month: 3, day: 26, text: "조용히 혼자 즐긴 시간의 의미는?" },
  { month: 3, day: 27, text: "올해 봄에 꼭 해보고 싶은 것은?" },
  { month: 3, day: 28, text: "마음이 설레던 대화가 있었다면?" },
  { month: 3, day: 29, text: "지금의 나를 한 단어로 부른다면?" },
  { month: 3, day: 30, text: "봄이 주는 여유, 어떻게 썼나요?" },
  { month: 3, day: 31, text: "이번 달 가장 선명한 기억은?" },
] as const;
