/** 3월 — 31일 (봄) */
export const MONTH_3_SEEDS = [
  { month: 3, day: 1, text: "새로 시작하고 싶은 마음이 들었던 날이 있었나요? 그날의 느낌을 이야기해주세요", tags: ["growth","hope"] },
  { month: 3, day: 2, text: "익숙한 것에서 벗어나 새로 시도했던 경험이 있나요? 그 순간을 이야기해주세요", tags: ["growth","experience"] },
  { month: 3, day: 3, text: "낮이 길어지는 시기에 떠오르는 기억이 있나요? 그 기억을 이야기해주세요", tags: ["weather","memory"] },
  { month: 3, day: 4, text: "어른이 되면서 달라진 생각이 있나요? 그 변화를 이야기해주세요", tags: ["growth","reflection"] },
  { month: 3, day: 5, text: "기다렸던 것이 드디어 와 닿았던 적이 있나요? 그때의 마음을 이야기해주세요", tags: ["hope","experience"] },
  { month: 3, day: 6, text: "매일 꾸준히 하고 있는 것이 있나요? 그 습관을 이야기해주세요", tags: ["growth","daily"] },
  { month: 3, day: 7, text: "산책하며 마음이 가벼워졌던 길이 있나요? 그 장소를 이야기해주세요", tags: ["experience","place"] },
  { month: 3, day: 8, text: "아직 찾지 못한 나의 모습이 있나요? 그 모습을 상상하며 이야기해주세요", tags: ["growth","self"] },
  { month: 3, day: 9, text: "작년 이맘때와 비교했을 때 달라진 점이 있나요? 그 변화를 이야기해주세요", tags: ["reflection","memory"] },
  { month: 3, day: 10, text: "실패에서 배운 교훈이 있나요? 그 경험을 이야기해주세요", tags: ["growth","experience"] },
  { month: 3, day: 11, text: "바람 부는 날 마음이 어디로 향했는지 이야기해주세요", tags: ["weather","emotion"] },
  { month: 3, day: 12, text: "처음으로 스스로를 자랑스러워했던 순간이 있나요? 그 순간을 이야기해주세요", tags: ["growth","hope"] },
  { month: 3, day: 13, text: "오래 간직하고 있는 물건이 있나요? 그 물건과 연결된 이야기를 해주세요", tags: ["experience","object"] },
  { month: 3, day: 14, text: "경험이 쌓이면서 바뀐 가치관이 있나요? 그 변화를 이야기해주세요", tags: ["growth","reflection"] },
  { month: 3, day: 15, text: "햇살 좋은 날 하고 싶었던 일이 있나요? 그 마음을 이야기해주세요", tags: ["daily","hope"] },
  { month: 3, day: 16, text: "끝까지 해냈던 경험이 있나요? 그때의 순간을 이야기해주세요", tags: ["growth","experience"] },
  { month: 3, day: 17, text: "언젠가 꼭 가보고 싶은 곳이 있나요? 그곳에 대한 마음을 이야기해주세요", tags: ["hope","future"] },
  { month: 3, day: 18, text: "최근에 새롭게 알게 된 것이 있나요? 그 깨달음을 이야기해주세요", tags: ["growth","emotion"] },
  { month: 3, day: 19, text: "비 뒤 공기와 함께 떠오르는 향이 있나요? 그 기억을 이야기해주세요", tags: ["memory","scent"] },
  { month: 3, day: 20, text: "잘하고 있다고 느끼는 영역이 있나요? 그 이유를 이야기해주세요", tags: ["growth","self"] },
  { month: 3, day: 21, text: "작은 변화가 보이는 풍경을 보며 느꼈던 감정이 있나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 3, day: 22, text: "인생에서 가장 큰 깨달음을 받았던 순간이 있나요? 그 순간을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 3, day: 23, text: "작은 친절에 마음이 움직였던 적이 있나요? 그 순간을 이야기해주세요", tags: ["hope","experience"] },
  { month: 3, day: 24, text: "요즘 빠져 있는 취미가 있나요? 그 취미에 대해 이야기해주세요", tags: ["growth","daily"] },
  { month: 3, day: 25, text: "자주 가고 싶어지는 장소가 있나요? 그 장소를 이야기해주세요", tags: ["weather","place"] },
  { month: 3, day: 26, text: "익숙함을 벗어난 선택을 한 적이 있나요? 그 경험을 이야기해주세요", tags: ["growth","experience"] },
  { month: 3, day: 27, text: "책이나 글 중 마음에 남은 한 구절이 있나요? 그 구절을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 3, day: 28, text: "언젠가 꼭 해보고 싶은 말 한마디가 있나요? 그 말을 이야기해주세요", tags: ["growth","hope"] },
  { month: 3, day: 29, text: "성장했다고 느낀 순간은 언제였나요? 그때의 순간을 이야기해주세요", tags: ["experience","self"] },
  { month: 3, day: 30, text: "계절이 바뀔 때마다 달라지는 기분이 있나요? 그 기분을 이야기해주세요", tags: ["emotion","reflection"] },
  { month: 3, day: 31, text: "시간이 더 주어진다면 무엇을 더 하고 싶나요? 그 마음을 이야기해주세요", tags: ["growth","future"] },
] as const;
