/** 4월 — 30일 */
export const MONTH_4_SEEDS = [
  { month: 4, day: 1, text: "꽃피는 계절, 마음도 함께 피웠나요?" },
  { month: 4, day: 2, text: "가벼운 기대를 품게 한 일은?" },
  { month: 4, day: 3, text: "벚꽃이나 봄꽃을 보며 느낀 것은?" },
  { month: 4, day: 4, text: "듣고 싶었던 말이 오늘 떠올랐나요?" },
  { month: 4, day: 5, text: "누군가와 함께한 봄날이 기억나나요?" },
  { month: 4, day: 6, text: "바람에 흔들리는 나뭇잎을 보며 잠시 멈췄나요?" },
  { month: 4, day: 7, text: "최근 마음이 움직인 순간은?" },
  { month: 4, day: 8, text: "봄날의 공기, 어떤 기억을 불러왔나요?" },
  { month: 4, day: 9, text: "낯선 이의 친절이 남긴 흔적은?" },
  { month: 4, day: 10, text: "말하지 못한 감사가 있다면 누구에게인가요?" },
  { month: 4, day: 11, text: "산책하며 발견한 작은 아름다움은?" },
  { month: 4, day: 12, text: "힘들었던 날의 나에게 건네고 싶은 말은?" },
  { month: 4, day: 13, text: "봄 햇살 아래 느낀 평화는?" },
  { month: 4, day: 14, text: "시간을 잊고 몰입했던 일은?" },
  { month: 4, day: 15, text: "예전 봄날이 그리워진 이유는?" },
  { month: 4, day: 16, text: "다가올 일을 떠올리며 설렌 적이 있나요?" },
  { month: 4, day: 17, text: "창밖 하늘의 색이 마음에 남았나요?" },
  { month: 4, day: 18, text: "최근 감동받은 이야기나 장면은?" },
  { month: 4, day: 19, text: "봄비 소리를 들으며 생각한 것은?" },
  { month: 4, day: 20, text: "오늘의 나에게 작은 선물을 한다면?" },
  { month: 4, day: 21, text: "같이 웃었던 그날의 풍경은?" },
  { month: 4, day: 22, text: "요즘 마음에 드는 취향이나 취미는?" },
  { month: 4, day: 23, text: "봄날 사진 속 나의 표정은 어땠나요?" },
  { month: 4, day: 24, text: "인연이 바꾼 내 삶의 한 페이지는?" },
  { month: 4, day: 25, text: "꽃을 건네거나 받았던 기억은?" },
  { month: 4, day: 26, text: "따뜻한 맛이나 향이 위로가 된 적은?" },
  { month: 4, day: 27, text: "봄밤 창밖을 보며 느낀 감정은?" },
  { month: 4, day: 28, text: "올해 봄에 처음 깨달은 것은?" },
  { month: 4, day: 29, text: "손에서 놓아도 괜찮을 것 같다고 느낀 것은?" },
  { month: 4, day: 30, text: "이번 달 마음에 남는 풍경 한 장면은?" },
] as const;
