/** 4월 — 30일 (봄) */
export const MONTH_4_SEEDS = [
  { month: 4, day: 1, text: "최근에 마음이 편안해졌던 하루가 있었나요? 그 하루를 이야기해주세요", tags: ["daily","emotion"] },
  { month: 4, day: 2, text: "마음이 끌리는 풍경이 있나요? 그곳과 연결된 기억을 이야기해주세요", tags: ["place","memory"] },
  { month: 4, day: 3, text: "사랑의 형태는 여러 가지라고 느꼈던 순간이 있나요? 그 순간을 이야기해주세요", tags: ["relationship","gratitude"] },
  { month: 4, day: 4, text: "요즘 자주 가는 장소가 있나요? 그 장소가 주는 느낌을 이야기해주세요", tags: ["daily","place"] },
  { month: 4, day: 5, text: "꽃이나 풀을 보며 마음이 함께 피었던 기억이 있나요? 그 기억을 이야기해주세요", tags: ["weather","memory"] },
  { month: 4, day: 6, text: "관계에서 배운 가장 큰 교훈이 있나요? 그 교훈을 이야기해주세요", tags: ["relationship","reflection"] },
  { month: 4, day: 7, text: "소소한 행복 하나를 떠올릴 수 있나요? 그 순간을 이야기해주세요", tags: ["daily","hope"] },
  { month: 4, day: 8, text: "자연 속에서 힐링했던 경험이 있나요? 그 경험을 이야기해주세요", tags: ["place","emotion"] },
  { month: 4, day: 9, text: "다른 사람의 이야기에 깊이 공감했던 적이 있나요? 그 순간을 이야기해주세요", tags: ["relationship","experience"] },
  { month: 4, day: 10, text: "하루 중 가장 조용한 시간이 있나요? 그 시간에 무엇을 하는지 이야기해주세요", tags: ["daily","reflection"] },
  { month: 4, day: 11, text: "하늘을 올려다본 마지막 순간을 떠올릴 수 있나요? 그때의 마음을 이야기해주세요", tags: ["weather","place"] },
  { month: 4, day: 12, text: "위로가 필요한 사람에게 해주고 싶은 말이 있나요? 그 말을 이야기해주세요", tags: ["relationship","hope"] },
  { month: 4, day: 13, text: "혼자 먹어도 행복한 메뉴가 있나요? 그 음식에 대해 이야기해주세요", tags: ["daily","food"] },
  { month: 4, day: 14, text: "고향이나 어릴 적 집을 떠올리면 어떤 장면이 보이나요? 그 기억을 이야기해주세요", tags: ["memory","place"] },
  { month: 4, day: 15, text: "좋아하는 사람의 어떤 점이 마음에 드나요? 그 이유를 이야기해주세요", tags: ["relationship","emotion"] },
  { month: 4, day: 16, text: "비 뒤 맑아진 하늘을 보며 느꼈던 감정이 있나요? 그 감정을 이야기해주세요", tags: ["daily","weather"] },
  { month: 4, day: 17, text: "함께 살고 싶은 공간의 모습을 상상해 본 적이 있나요? 그 모습을 이야기해주세요", tags: ["relationship","memory"] },
  { month: 4, day: 18, text: "집이나 방이 어떤 상태일 때 마음이 편한가요? 그 이유를 이야기해주세요", tags: ["daily","self"] },
  { month: 4, day: 19, text: "바람 맞으며 걸으면 어떤 생각이 드나요? 그 생각을 이야기해주세요", tags: ["weather","experience"] },
  { month: 4, day: 20, text: "누군가의 도움으로 버텼던 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["relationship","gratitude"] },
  { month: 4, day: 21, text: "집에서 가장 편안한 공간은 어디인가요? 그 공간에 대해 이야기해주세요", tags: ["daily","place"] },
  { month: 4, day: 22, text: "어릴 적 가장 좋아했던 계절이 있나요? 그 계절의 기억을 이야기해주세요", tags: ["memory","weather"] },
  { month: 4, day: 23, text: "다시 만나고 싶은 사람이 있나요? 그 사람과의 기억을 이야기해주세요", tags: ["relationship","experience"] },
  { month: 4, day: 24, text: "요즘 가장 자주 드는 감정이 있나요? 그 감정을 이야기해주세요", tags: ["daily","emotion"] },
  { month: 4, day: 25, text: "지금 사는 곳에서 좋아하는 점이 있나요? 그 이유를 이야기해주세요", tags: ["place","hope"] },
  { month: 4, day: 26, text: "당신에게 잘하고 있다고 말해 주고 싶은 사람이 있나요? 그 마음을 이야기해주세요", tags: ["relationship","reflection"] },
  { month: 4, day: 27, text: "좋아하는 향이나 냄새가 있나요? 그 향과 연결된 기억을 이야기해주세요", tags: ["daily","scent"] },
  { month: 4, day: 28, text: "창밖 풍경을 바라보며 쉬는 시간이 있나요? 그 순간을 이야기해주세요", tags: ["weather","memory"] },
  { month: 4, day: 29, text: "일상에서 작은 의식 같은 것이 있나요? 그 의식을 이야기해주세요", tags: ["relationship","daily"] },
  { month: 4, day: 30, text: "행운이라고 느낀 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
] as const;
