/** 5월 — 31일 */
export const MONTH_5_SEEDS = [
  { month: 5, day: 1, text: "초여름 바람, 어디로 가고 싶었나요?" },
  { month: 5, day: 2, text: "활력을 주었던 사람이나 장소는?" },
  { month: 5, day: 3, text: "녹음이 짙어지는 길에서 생각한 것은?" },
  { month: 5, day: 4, text: "오늘 마음이 환해진 계기는?" },
  { month: 5, day: 5, text: "어릴 적 5월의 기억이 있다면?" },
  { month: 5, day: 6, text: "뜻밖의 웃음을 선사한 하루는?" },
  { month: 5, day: 7, text: "따스한 날씨에 하고 싶었던 일은?" },
  { month: 5, day: 8, text: "감사가 밀려온 순간은 언제였나요?" },
  { month: 5, day: 9, text: "하루의 리듬을 지켜주는 습관은?" },
  { month: 5, day: 10, text: "꽃향기나 풀냄새가 떠올린 장면은?" },
  { month: 5, day: 11, text: "쉬어야 한다고 몸이 말한 때는?" },
  { month: 5, day: 12, text: "따뜻한 말을 건넸던 사람이 떠오르나요?" },
  { month: 5, day: 13, text: "햇빛 아래서 느낀 행복은?" },
  { month: 5, day: 14, text: "앞날을 그리며 두근거린 적이 있나요?" },
  { month: 5, day: 15, text: "옛날 5월이 그리워진 이유는?" },
  { month: 5, day: 16, text: "대화 하나가 마음을 바꾼 적이 있나요?" },
  { month: 5, day: 17, text: "초여름 밤, 창문 너머 풍경은?" },
  { month: 5, day: 18, text: "몸과 마음이 가장 편했던 시간대는?" },
  { month: 5, day: 19, text: "작은 성취 뒤 느낀 자신감은?" },
  { month: 5, day: 20, text: "사랑하는 사람과의 장면이 떠오르나요?" },
  { month: 5, day: 21, text: "듣고 싶은 음악의 분위기는 어떤가요?" },
  { month: 5, day: 22, text: "돌이켜보면 잘한 선택이 있다면?" },
  { month: 5, day: 23, text: "초여름 산책에서 본 하늘은?" },
  { month: 5, day: 24, text: "어제의 나에게 고마웠던 점은?" },
  { month: 5, day: 25, text: "봄과 여름 사이, 마음의 계절은?" },
  { month: 5, day: 26, text: "오늘의 기쁨을 누구와 나누고 싶나요?" },
  { month: 5, day: 27, text: "오늘부터 시작하고 싶은 것은?" },
  { month: 5, day: 28, text: "거리나 자연이 건넨 위로는?" },
  { month: 5, day: 29, text: "이번 달 가장 빛났던 하루는?" },
  { month: 5, day: 30, text: "내일이 기다려지게 한 것은?" },
  { month: 5, day: 31, text: "5월을 떠나내며 남기고 싶은 한마디는?" },
] as const;
