/** 5월 — 31일 (봄) */
export const MONTH_5_SEEDS = [
  { month: 5, day: 1, text: "당신을 가장 설레게 하는 일이 있나요? 그 일에 대해 이야기해주세요", tags: ["experience","emotion"] },
  { month: 5, day: 2, text: "작은 선택이 큰 변화를 만든 적이 있나요? 그 경험을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 5, day: 3, text: "바람을 맞으며 마음이 가벼워졌던 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","hope"] },
  { month: 5, day: 4, text: "활력을 주었던 사람이나 장소가 있나요? 그것을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 5, day: 5, text: "처음 해본 일 중 기억에 남는 것이 있나요? 그 경험을 이야기해주세요", tags: ["experience","memory"] },
  { month: 5, day: 6, text: "일상에 작은 변화를 주면 기분이 달라지나요? 그 변화를 이야기해주세요", tags: ["growth","reflection"] },
  { month: 5, day: 7, text: "길을 걸으며 생각이 깊어지던 순간이 있나요? 그 생각을 이야기해주세요", tags: ["experience","place"] },
  { month: 5, day: 8, text: "상상만 해도 즐거운 장면이 떠오르나요? 그 장면을 이야기해주세요", tags: ["experience","hope"] },
  { month: 5, day: 9, text: "앞으로 다가올 변화를 떠올릴 때 어떤 마음이 드나요? 그 마음을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 5, day: 10, text: "설레는 마음을 마지막으로 느낀 때가 있나요? 그때의 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 5, day: 11, text: "나는 무엇에 감동을 받는 사람인가요? 최근에 감동받은 순간을 이야기해주세요", tags: ["experience","self"] },
  { month: 5, day: 12, text: "평소와 다르게 하루를 보낸 적이 있나요? 그 하루를 이야기해주세요", tags: ["daily","reflection"] },
  { month: 5, day: 13, text: "기발한 아이디어를 떠올린 적이 있나요? 그 아이디어를 이야기해주세요", tags: ["experience","future"] },
  { month: 5, day: 14, text: "누군가를 응원하고 싶은 마음이 든 적이 있나요? 그 마음을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 5, day: 15, text: "포기했지만 아직 마음에 남아 있는 것이 있나요? 그것을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 5, day: 16, text: "작은 선물을 받았을 때 기억나는 것이 있나요? 그 순간을 이야기해주세요", tags: ["experience","object"] },
  { month: 5, day: 17, text: "시간이 멈췄으면 하는 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 5, day: 18, text: "다시 선택한다면 바꾸고 싶은 순간이 있나요? 그 순간을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 5, day: 19, text: "새로운 것을 시도했던 날이 있었나요? 그날을 이야기해주세요", tags: ["experience","daily"] },
  { month: 5, day: 20, text: "세상이 조금 더 따뜻해졌으면 하는 것이 있나요? 그것을 이야기해주세요", tags: ["experience","hope"] },
  { month: 5, day: 21, text: "새로운 이름이나 별명을 지어 본 적이 있나요? 그 경험을 이야기해주세요", tags: ["self","reflection"] },
  { month: 5, day: 22, text: "작은 선행을 실천한 적이 있나요? 그때의 마음을 이야기해주세요", tags: ["experience","gratitude"] },
  { month: 5, day: 23, text: "좋아하는 영화나 드라마 장면이 떠오르나요? 왜 기억에 남는지 이야기해주세요", tags: ["experience","memory"] },
  { month: 5, day: 24, text: "스스로에게 실망했던 순간이 있었나요? 그때의 마음을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 5, day: 25, text: "걷기만 해도 생각이 정리되는 길이 있나요? 그 길을 이야기해주세요", tags: ["experience","place"] },
  { month: 5, day: 26, text: "가장 행복했던 나이를 떠올릴 수 있나요? 그때의 기억을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 5, day: 27, text: "내일부터 시작하고 싶은 것이 있나요? 그것을 이야기해주세요", tags: ["hope","reflection"] },
  { month: 5, day: 28, text: "연애에서 배운 것이 있나요? 그 배움을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 5, day: 29, text: "칭찬받고 싶은 부분이 있나요? 그 이유를 이야기해주세요", tags: ["experience","self"] },
  { month: 5, day: 30, text: "만약 다른 길을 선택했다면 어떤 모습일까요? 상상하며 이야기해주세요", tags: ["future","reflection"] },
  { month: 5, day: 31, text: "성취 후 비어 있는 기분을 느낀 적이 있나요? 그 경험을 이야기해주세요", tags: ["experience","reflection"] },
] as const;
