/** 6월 — 30일 */
export const MONTH_6_SEEDS = [
  { month: 6, day: 1, text: "긴 낮, 오늘 가장 밝았던 순간은?" },
  { month: 6, day: 2, text: "여름 초입, 나를 설레게 한 것은?" },
  { month: 6, day: 3, text: "시원함이 필요했던 순간은?" },
  { month: 6, day: 4, text: "여유를 느낀 때는 언제였나요?" },
  { month: 6, day: 5, text: "어린 적 여름 기억이 떠오른다면?" },
  { month: 6, day: 6, text: "햇살 아래서 잠시 쉬며 생각한 것은?" },
  { month: 6, day: 7, text: "최근 나를 편하게 해준 사람은?" },
  { month: 6, day: 8, text: "물가를 떠올리게 한 장면은?" },
  { month: 6, day: 9, text: "소중히 지키고 있는 일상은?" },
  { month: 6, day: 10, text: "여름밤 공기, 어떤 감정을 불러왔나요?" },
  { month: 6, day: 11, text: "웃음이 터졌던 장면은?" },
  { month: 6, day: 12, text: "예전 6월이 그리워진 이유는?" },
  { month: 6, day: 13, text: "작은 모험을 떠올리게 한 일은?" },
  { month: 6, day: 14, text: "스스로를 인정해 주고 싶은 순간은?" },
  { month: 6, day: 15, text: "따뜻한 저녁, 누구와 함께였나요?" },
  { month: 6, day: 16, text: "요즘 귀에 맴도는 노래는?" },
  { month: 6, day: 17, text: "기다려지는 약속이 있나요?" },
  { month: 6, day: 18, text: "나를 버티게 해준 말은?" },
  { month: 6, day: 19, text: "여름 비 뒤 맑아진 하늘을 보며 느낀 것은?" },
  { month: 6, day: 20, text: "나를 여기까지 온 인연은?" },
  { month: 6, day: 21, text: "쉼 없이 달리다 멈춘 이유는?" },
  { month: 6, day: 22, text: "그리운 맛이나 향이 있다면?" },
  { month: 6, day: 23, text: "어제의 나에게 전하고 싶은 말은?" },
  { month: 6, day: 24, text: "여름날 창밖 풍경이 전한 메시지는?" },
  { month: 6, day: 25, text: "함께 웃었던 그날이 떠오르나요?" },
  { month: 6, day: 26, text: "마음에서 내려놓으면 편해질 것은?" },
  { month: 6, day: 27, text: "올해 여름에 꼭 해보고 싶은 것은?" },
  { month: 6, day: 28, text: "고요해지게 만든 풍경은?" },
  { month: 6, day: 29, text: "이번 달 가장 선명한 웃음은?" },
  { month: 6, day: 30, text: "6월의 끝, 마음에 남는 색은?" },
] as const;
