/** 6월 — 30일 (여름) */
export const MONTH_6_SEEDS = [
  { month: 6, day: 1, text: "운동이나 산책을 하면 기분이 어떻게 달라지나요?" },
  { month: 6, day: 2, text: "좋아하는 운동이나 활동이 있나요?" },
  { month: 6, day: 3, text: "함께 운동하고 싶은 사람이 있나요?" },
  { month: 6, day: 4, text: "오늘 몸을 위해 한 일이 있나요?" },
  { month: 6, day: 5, text: "건강을 위해서 어떤 노력을 하고 있나요?" },
  { month: 6, day: 6, text: "건강을 위해 줄이려고 노력하는 것이 있나요?" },
  { month: 6, day: 7, text: "수면 습관에서 바꾸고 싶은 점이 있나요?" },
  { month: 6, day: 8, text: "요즘 몸과 마음을 위해 각각 하고 있는 일이 있나요? 이야기해주세요" },
  { month: 6, day: 9, text: "최근에 몸이 가벼워졌다고 느낀 적이 있나요?" },
  { month: 6, day: 10, text: "건강 검진이나 병원, 잘 챙기고 있나요?" },
  { month: 6, day: 11, text: "스트레스가 몸에 어떻게 나타나나요?" },
  { month: 6, day: 12, text: "불안할 때 몸은 어떤 반응을 하나요?" },
  { month: 6, day: 13, text: "요즘 몸을 많이 쓰고 있나요?" },
  { month: 6, day: 14, text: "춤추거나 몸을 풀면 기분이 어떤가요?" },
  { month: 6, day: 15, text: "몸이 기억하는 즐거운 움직임이 있나요?" },
  { month: 6, day: 16, text: "잊지 못할 여행이 있나요?" },
  { month: 6, day: 17, text: "모험을 떠나고 싶은 마음이 있나요?" },
  { month: 6, day: 18, text: "뉴스나 SNS를 보며 마음이 무거워진 적이 있나요?" },
  { month: 6, day: 19, text: "누군가를 응원하고 싶은 마음이 든 적이 있나요?" },
  { month: 6, day: 20, text: "세상이 조금 더 따뜻해졌으면 하는 것은?" },
  { month: 6, day: 21, text: "타인과 비교하며 힘들었던 적이 있나요?" },
  { month: 6, day: 22, text: "작은 선행을 실천한 적이 있나요?" },
  { month: 6, day: 23, text: "시간이 빨리 간다고 느끼나요?" },
  { month: 6, day: 24, text: "소중한 시간을 누구와 보내고 싶나요?" },
  { month: 6, day: 25, text: "바쁘다고 느끼는 요즘, 진짜 바쁜가요?" },
  { month: 6, day: 26, text: "여유를 갖기 위해 줄이고 싶은 것은?" },
  { month: 6, day: 27, text: "지금 이 나이의 장점은 무엇인가요?" },
  { month: 6, day: 28, text: "오늘 하루를 어떻게 보냈다고 말하고 싶나요?" },
  { month: 6, day: 29, text: "오늘 하고 싶은 말을 아직 하지 못했다면?" },
  { month: 6, day: 30, text: "말 대신 행동으로 전한 적이 있나요?" },
] as const;
