/** 6월 — 30일 (여름) */
export const MONTH_6_SEEDS = [
  { month: 6, day: 1, text: "하루 중 가장 밝았던 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 6, day: 2, text: "운동이나 산책을 하면 기분이 어떻게 달라지나요? 그 느낌을 이야기해주세요", tags: ["daily","experience"] },
  { month: 6, day: 3, text: "좋아하는 운동이나 활동이 있나요? 그 활동에 대해 이야기해주세요", tags: ["experience","self"] },
  { month: 6, day: 4, text: "같이 있으면 마음이 편해지는 사람이 있나요? 그 사람과의 순간을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 6, day: 5, text: "몸을 위해 한 일이 있었나요? 그 경험을 이야기해주세요", tags: ["daily","experience"] },
  { month: 6, day: 6, text: "지금 나에게 필요한 쉬어가기가 있다면 무엇인가요? 그것을 이야기해주세요", tags: ["experience","hope"] },
  { month: 6, day: 7, text: "최근 나를 설레게 한 것이 있나요? 그것을 이야기해주세요", tags: ["experience","hope"] },
  { month: 6, day: 8, text: "요즘 몸과 마음을 위해 각각 하고 있는 일이 있나요? 이야기해주세요", tags: ["daily","experience"] },
  { month: 6, day: 9, text: "최근에 몸이 가벼워졌다고 느낀 적이 있나요? 그때의 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 6, day: 10, text: "몸이 기억하는 즐거운 움직임이 있나요? 그 움직임을 이야기해주세요", tags: ["experience","memory"] },
  { month: 6, day: 11, text: "수면 습관에서 바꾸고 싶은 점이 있나요? 그 이유를 이야기해주세요", tags: ["daily","reflection"] },
  { month: 6, day: 12, text: "걸음이 느려지며 생각이 정리되던 길이 있나요? 그 경험을 이야기해주세요", tags: ["experience","place"] },
  { month: 6, day: 13, text: "몸을 움직이며 마음이 달라졌던 적이 있나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 6, day: 14, text: "하루 중 기분이 가장 좋은 시간대가 있나요? 그 시간에 무엇을 하는지 이야기해주세요", tags: ["daily","experience"] },
  { month: 6, day: 15, text: "나만의 컨디션 회복 방법이 있다면 무엇인가요? 그 방법을 이야기해주세요", tags: ["experience","hope"] },
  { month: 6, day: 16, text: "스트레스가 몸에 어떻게 나타나나요? 그 경험을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 6, day: 17, text: "지친 하루 속에서도 좋았던 것이 있나요? 그것을 이야기해주세요", tags: ["daily","experience"] },
  { month: 6, day: 18, text: "바쁠 때도 잊지 않고 지키는 나만의 방식이 있나요? 그 방식을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 6, day: 19, text: "불안할 때 몸은 어떤 반응을 하나요? 그 경험을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 6, day: 20, text: "저녁 시간을 어떻게 보내고 있나요? 그 시간에 대해 이야기해주세요", tags: ["daily","experience"] },
  { month: 6, day: 21, text: "밤하늘을 보며 떠올린 것이 있나요? 그 생각을 이야기해주세요", tags: ["experience","memory"] },
  { month: 6, day: 22, text: "건강을 위해 줄이려고 노력하는 것이 있나요? 그 노력을 이야기해주세요", tags: ["growth","daily"] },
  { month: 6, day: 23, text: "밤바람이 전해준 느낌이 있었나요? 그 느낌을 이야기해주세요", tags: ["experience","weather"] },
  { month: 6, day: 24, text: "내가 지치고 힘들 때 보통 어떻게 행동하나요? 그 방식을 이야기해주세요", tags: ["daily","reflection"] },
  { month: 6, day: 25, text: "바다나 강, 호수를 떠올리게 한 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","place"] },
  { month: 6, day: 26, text: "친구나 가족과 나눈 따뜻한 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 6, day: 27, text: "요즘 마음이 무거울 때 어떻게 버티고 있나요? 그 방법을 이야기해주세요", tags: ["daily","emotion"] },
  { month: 6, day: 28, text: "힘든 시기에도 지켜진 것이 있나요? 그 순간을 이야기해주세요", tags: ["experience","hope"] },
  { month: 6, day: 29, text: "스스로를 다독여 준 적이 있나요? 그때의 마음을 이야기해주세요", tags: ["experience","self"] },
  { month: 6, day: 30, text: "휴식이 필요했던 이유가 있었나요? 그 이유를 이야기해주세요", tags: ["daily","reflection"] },
] as const;
