/** 7월 — 31일 */
export const MONTH_7_SEEDS = [
  { month: 7, day: 1, text: "한여름, 더위 속에서도 좋았던 것은?" },
  { month: 7, day: 2, text: "휴식이 필요했던 이유는?" },
  { month: 7, day: 3, text: "밤하늘을 보며 떠올린 것이 있다면?" },
  { month: 7, day: 4, text: "마음이 시원해진 순간은?" },
  { month: 7, day: 5, text: "어릴 적 여름방학 기억은?" },
  { month: 7, day: 6, text: "의외로 좋았던 하루는?" },
  { month: 7, day: 7, text: "친구·가족과 나눈 따뜻한 순간은?" },
  { month: 7, day: 8, text: "예전 7월이 그리워진 이유는?" },
  { month: 7, day: 9, text: "시원한 바람이 불어온 장면은?" },
  { month: 7, day: 10, text: "위로가 되었던 말이나 행동은?" },
  { month: 7, day: 11, text: "여름날 산책에서 본 풍경은?" },
  { month: 7, day: 12, text: "나를 지금의 나로 만든 경험은?" },
  { month: 7, day: 13, text: "마음이 편해진 계기는?" },
  { month: 7, day: 14, text: "사랑하는 장소로 떠나고 싶은 마음은?" },
  { month: 7, day: 15, text: "말하지 못한 감사가 있다면?" },
  { month: 7, day: 16, text: "여름밤 불빛 아래 느낀 감정은?" },
  { month: 7, day: 17, text: "힘들었던 날의 나를 어루만지고 싶은 이유는?" },
  { month: 7, day: 18, text: "몸과 마음을 돌본 방법은?" },
  { month: 7, day: 19, text: "요즘 아끼는 취미나 습관은?" },
  { month: 7, day: 20, text: "내일의 나에게 건네고 싶은 말은?" },
  { month: 7, day: 21, text: "함께 웃었던 여름날이 떠오르나요?" },
  { month: 7, day: 22, text: "마음속 여행지는 어디인가요?" },
  { month: 7, day: 23, text: "여름밤, 앞으로의 나를 상상하며 느낀 것은?" },
  { month: 7, day: 24, text: "여름 비 소리를 들으며 생각한 것은?" },
  { month: 7, day: 25, text: "다시 살고 싶은 하루의 순간은?" },
  { month: 7, day: 26, text: "스스로를 칭찬해 주고 싶은 일은?" },
  { month: 7, day: 27, text: "소중한 관계가 있다면 어떤 점인가요?" },
  { month: 7, day: 28, text: "한여름의 햇살이 전한 메시지는?" },
  { month: 7, day: 29, text: "이번 달 가장 기억에 남는 맛은?" },
  { month: 7, day: 30, text: "여름의 끝을 앞두며 느낀 것은?" },
  { month: 7, day: 31, text: "7월을 한 문장으로 남긴다면?" },
] as const;
