/** 7월 — 31일 (여름) */
export const MONTH_7_SEEDS = [
  { month: 7, day: 1, text: "잊지 못할 여행이 있나요? 그 여행의 기억을 이야기해주세요", tags: ["experience","memory"] },
  { month: 7, day: 2, text: "모험을 떠나고 싶은 마음이 든 적이 있나요? 그 마음을 이야기해주세요", tags: ["experience","hope"] },
  { month: 7, day: 3, text: "혼자 여행을 가 본 적이 있나요? 그 경험을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 7, day: 4, text: "한 해의 중간, 지금까지의 나를 돌아보며 떠오르는 것이 있나요? 이야기해주세요", tags: ["reflection","memory"] },
  { month: 7, day: 5, text: "처음 도착했을 때 마음이 편해진 장소가 있나요? 그 장소를 이야기해주세요", tags: ["experience","place"] },
  { month: 7, day: 6, text: "낯선 곳에서 느꼈던 설렘이 있었나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 7, day: 7, text: "올해 가장 잘한 선택은 무엇인가요? 그 선택에 대해 이야기해주세요", tags: ["reflection","growth"] },
  { month: 7, day: 8, text: "여행지에서 기억에 남는 소리가 있나요? 그 소리를 이야기해주세요", tags: ["experience","sound"] },
  { month: 7, day: 9, text: "먼 곳에서 먹었던 음식 중 잊지 못하는 것이 있나요? 그 기억을 이야기해주세요", tags: ["experience","food"] },
  { month: 7, day: 10, text: "지금 이 나이의 장점은 무엇인가요? 그 장점을 이야기해주세요", tags: ["reflection","self"] },
  { month: 7, day: 11, text: "여행 중 만난 날씨가 기억에 남나요? 그날을 이야기해주세요", tags: ["experience","weather"] },
  { month: 7, day: 12, text: "소중한 시간을 누구와 보내고 싶나요? 그 마음을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 7, day: 13, text: "바쁘다고 느끼는 요즘, 진짜 바쁜가요? 그 생각을 이야기해주세요", tags: ["reflection","hope"] },
  { month: 7, day: 14, text: "여행에서 가져온 물건이 있나요? 그 물건의 이야기를 해주세요", tags: ["experience","object"] },
  { month: 7, day: 15, text: "길을 잃었을 때 어떻게 선택했나요? 그 경험을 이야기해주세요", tags: ["experience","memory"] },
  { month: 7, day: 16, text: "여유를 갖기 위해 줄이고 싶은 것이 있나요? 그것을 이야기해주세요", tags: ["reflection","daily"] },
  { month: 7, day: 17, text: "다시 가고 싶은 여행지가 있나요? 그곳에 대한 기억을 이야기해주세요", tags: ["experience","place"] },
  { month: 7, day: 18, text: "이동하는 시간에 어떤 생각을 하나요? 그 생각을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 7, day: 19, text: "지금의 고민이 1년 뒤에는 어떤 이야기가 될까요? 상상하며 이야기해주세요", tags: ["reflection","future"] },
  { month: 7, day: 20, text: "여행지에서 맡았던 향이 기억나나요? 그 향과 연결된 순간을 이야기해주세요", tags: ["experience","scent"] },
  { month: 7, day: 21, text: "지금 할 수 있는 가장 멋진 일은 무엇일까요? 그 일에 대해 이야기해주세요", tags: ["experience","hope"] },
  { month: 7, day: 22, text: "시간이 빨리 간다고 느낀 적이 있나요? 그때의 기억을 이야기해주세요", tags: ["reflection","daily"] },
  { month: 7, day: 23, text: "여행에서 만난 사람이 기억에 남나요? 그 만남을 이야기해주세요", tags: ["experience","relationship"] },
  { month: 7, day: 24, text: "스스로와의 약속, 지키고 있나요? 그 약속을 이야기해주세요", tags: ["reflection","self"] },
  { month: 7, day: 25, text: "출퇴근이나 이동 시간에 무엇을 하나요? 그 시간에 대해 이야기해주세요", tags: ["experience","memory"] },
  { month: 7, day: 26, text: "두려움을 넘어섰을 때 어떤 기분이었나요? 그 순간을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 7, day: 27, text: "더 나은 삶이란 당신에게 무엇일까요? 그 의미를 이야기해주세요", tags: ["reflection","hope"] },
  { month: 7, day: 28, text: "창문 밖 풍경을 좋아하나요? 그 풍경에 대해 이야기해주세요", tags: ["experience","place"] },
  { month: 7, day: 29, text: "매일 같은 길을 걸으며 생각한 적이 있나요? 그 생각을 이야기해주세요", tags: ["experience","daily"] },
  { month: 7, day: 30, text: "어두운 시기를 지나온 경험이 있나요? 그 경험을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 7, day: 31, text: "상상만 해도 설레는 계획이 있나요? 그 계획을 이야기해주세요", tags: ["experience","hope"] },
] as const;
