/** 8월 — 31일 (여름) */
export const MONTH_8_SEEDS = [
  { month: 8, day: 1, text: "기분에 따라 듣는 음악이 달라지나요? 그 음악에 대해 이야기해주세요", tags: ["experience","sound"] },
  { month: 8, day: 2, text: "노래 가사 중 마음에 남은 한 줄이 있나요? 그 가사를 이야기해주세요", tags: ["memory","sound"] },
  { month: 8, day: 3, text: "옛날 들었던 노래를 들으면 어떤 기분인가요? 그 기분을 이야기해주세요", tags: ["memory","sound"] },
  { month: 8, day: 4, text: "함께 듣던 음악이 떠오르는 사람이 있나요? 그 기억을 이야기해주세요", tags: ["relationship","sound"] },
  { month: 8, day: 5, text: "콘서트나 공연을 본 기억이 있나요? 그날을 이야기해주세요", tags: ["memory","experience"] },
  { month: 8, day: 6, text: "하루를 마무리할 때 듣는 음악이 있나요? 그 음악을 이야기해주세요", tags: ["experience","sound"] },
  { month: 8, day: 7, text: "좋아하는 목소리나 웃음소리가 있나요? 그 소리를 이야기해주세요", tags: ["memory","sound"] },
  { month: 8, day: 8, text: "위로가 되는 음식이 있나요? 그 음식과 연결된 기억을 이야기해주세요", tags: ["food","memory"] },
  { month: 8, day: 9, text: "처음 먹어 본 맛이 인상 깊었던 적이 있나요? 그 경험을 이야기해주세요", tags: ["experience","food"] },
  { month: 8, day: 10, text: "누군가와 나눴던 식사가 기억에 남나요? 그 식사를 이야기해주세요", tags: ["relationship","food"] },
  { month: 8, day: 11, text: "소리로 기억되는 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","sound"] },
  { month: 8, day: 12, text: "다른 사람의 조언을 따랐던 적이 있나요? 그 경험을 이야기해주세요", tags: ["relationship","experience"] },
  { month: 8, day: 13, text: "외로움을 느낀 적이 있나요? 그때 무엇을 했는지 이야기해주세요", tags: ["relationship","emotion"] },
  { month: 8, day: 14, text: "누군가에게 위로받고 싶은 마음이 든 적이 있나요? 그 마음을 이야기해주세요", tags: ["relationship","hope"] },
  { month: 8, day: 15, text: "특정 음식을 먹으며 떠올리는 사람이 있나요? 그 기억을 이야기해주세요", tags: ["experience","food"] },
  { month: 8, day: 16, text: "가족이나 가까운 사람과 나눈 말 중 기억에 남는 것이 있나요? 그 말을 이야기해주세요", tags: ["relationship","memory"] },
  { month: 8, day: 17, text: "비 오는 날 듣고 싶은 소리가 있나요? 그 소리를 이야기해주세요", tags: ["experience","sound"] },
  { month: 8, day: 18, text: "선물을 받거나 줄 때 어떤 기분인가요? 그 경험을 이야기해주세요", tags: ["relationship","gratitude"] },
  { month: 8, day: 19, text: "어머니나 가족이 해 주던 음식이 떠오르나요? 그 기억을 이야기해주세요", tags: ["memory","food"] },
  { month: 8, day: 20, text: "옛날 사진을 보면 어떤 기분이 드나요? 그 기분을 이야기해주세요", tags: ["relationship","memory"] },
  { month: 8, day: 21, text: "함께 웃으며 시간을 보냈던 사람이 떠오르나요? 그 순간을 이야기해주세요", tags: ["relationship","experience"] },
  { month: 8, day: 22, text: "혼자 있는 시간이 필요한가요? 그 필요에 대해 이야기해주세요", tags: ["relationship","self"] },
  { month: 8, day: 23, text: "맛보고 싶은 음식이 있나요? 그 음식에 대한 기대를 이야기해주세요", tags: ["experience","food"] },
  { month: 8, day: 24, text: "화가 날 때 당신만의 푸는 방법이 있나요? 그 방법을 이야기해주세요", tags: ["relationship","emotion"] },
  { month: 8, day: 25, text: "어릴 적 자주 들었던 소리가 기억나나요? 그 소리를 이야기해주세요", tags: ["memory","sound"] },
  { month: 8, day: 26, text: "다시 사랑할 준비가 되어 있다고 느끼나요? 그 마음을 이야기해주세요", tags: ["relationship","hope"] },
  { month: 8, day: 27, text: "카페나 식당에서 기억에 남는 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","food"] },
  { month: 8, day: 28, text: "이별이나 아픔을 겪은 적이 있나요? 그때의 마음을 이야기해주세요", tags: ["relationship","memory"] },
  { month: 8, day: 29, text: "오래 두고 싶은 사진이나 기록이 있나요? 그것과 연결된 이야기를 해주세요", tags: ["memory","object"] },
  { month: 8, day: 30, text: "혼자만의 공간이 있다면 어떤 모습인가요? 그 공간을 이야기해주세요", tags: ["relationship","place"] },
  { month: 8, day: 31, text: "음식 냄새만으로 떠오르는 기억이 있나요? 그 기억을 이야기해주세요", tags: ["experience","scent"] },
] as const;
