/** 8월 — 31일 */
export const MONTH_8_SEEDS = [
  { month: 8, day: 1, text: "8월의 시작, 마음이 향한 곳은?" },
  { month: 8, day: 2, text: "더운 날에도 기억에 남는 순간은?" },
  { month: 8, day: 3, text: "멀리 있어도 생각나는 사람은?" },
  { month: 8, day: 4, text: "여름밤 길을 걸으며 생각한 것은?" },
  { month: 8, day: 5, text: "8월 아침, 창문 밖 풍경이 전한 말은?" },
  { month: 8, day: 6, text: "최근 마음이 움직인 이야기는?" },
  { month: 8, day: 7, text: "어릴 적 8월의 기억이 있다면?" },
  { month: 8, day: 8, text: "오늘의 나에게 필요한 용기는?" },
  { month: 8, day: 9, text: "함께 나눈 여름의 웃음은?" },
  { month: 8, day: 10, text: "예전 8월이 그리워진 이유는?" },
  { month: 8, day: 11, text: "시원함이 마음까지 달랜 순간은?" },
  { month: 8, day: 12, text: "무더위 속에서도 웃게 해준 일은?" },
  { month: 8, day: 13, text: "몰입하느라 시간을 잊었던 순간은?" },
  { month: 8, day: 14, text: "8월에 새로 배우고 싶은 것은?" },
  { month: 8, day: 15, text: "빛나는 밤, 창밖을 보며 느낀 감정은?" },
  { month: 8, day: 16, text: "후회 없이 한 결정이 있다면?" },
  { month: 8, day: 17, text: "요즘 귀에 맴도는 노래의 한 구절은?" },
  { month: 8, day: 18, text: "어제 밤의 나에게 고마웠던 점은?" },
  { month: 8, day: 19, text: "여름 끝자락, 아쉬움이 남는 것은?" },
  { month: 8, day: 20, text: "다음 주가 기다려지는 이유는?" },
  { month: 8, day: 21, text: "오래 기다리던 말을 들은 적이 있나요?" },
  { month: 8, day: 22, text: "최근 성장에 도움이 된 경험은?" },
  { month: 8, day: 23, text: "거리의 풍경이 마음을 어루만진 적은?" },
  { month: 8, day: 24, text: "8월에 함께했던 사람의 웃음은?" },
  { month: 8, day: 25, text: "놓아도 후회 없을 마음의 짐은?" },
  { month: 8, day: 26, text: "올해 여름에 처음 깨달은 것은?" },
  { month: 8, day: 27, text: "스스로를 뿌듯하게 만든 순간은?" },
  { month: 8, day: 28, text: "8월 중 가장 행복했던 날은?" },
  { month: 8, day: 29, text: "여름의 색으로 남기고 싶은 장면은?" },
  { month: 8, day: 30, text: "8월을 떠나내며 남기고 싶은 한마디는?" },
  { month: 8, day: 31, text: "여름의 끝, 마음에 남는 풍경은?" },
] as const;
