/** 9월 — 30일 */
export const MONTH_9_SEEDS = [
  { month: 9, day: 1, text: "가을이 시작되며 마음이 바뀐 것은?" },
  { month: 9, day: 2, text: "선선한 바람, 어떤 기억을 불러왔나요?" },
  { month: 9, day: 3, text: "요즘 듣고 싶은 음악의 분위기는?" },
  { month: 9, day: 4, text: "새로운 시작을 앞두며 느낀 것은?" },
  { month: 9, day: 5, text: "어릴 적 9월의 기억이 있다면?" },
  { month: 9, day: 6, text: "9월 첫 주, 고마움을 느낀 일은?" },
  { month: 9, day: 7, text: "나를 지탱하는 하루의 패턴은?" },
  { month: 9, day: 8, text: "예전 9월이 그리워진 이유는?" },
  { month: 9, day: 9, text: "가을 하늘을 보며 생각한 것은?" },
  { month: 9, day: 10, text: "환한 마음을 만든 작은 계기는?" },
  { month: 9, day: 11, text: "작은 성과 뒤 느낀 뿌듯함은?" },
  { month: 9, day: 12, text: "누군가에게 건넨 따뜻한 한마디는?" },
  { month: 9, day: 13, text: "하루 중 몸이 가장 편했던 때는?" },
  { month: 9, day: 14, text: "앞으로의 길을 그리며 두근거렸나요?" },
  { month: 9, day: 15, text: "전하지 못한 고마움이 떠오르나요?" },
  { month: 9, day: 16, text: "가을날 산책에서 본 풍경은?" },
  { month: 9, day: 17, text: "우연히 만난 인연이 남긴 것은?" },
  { month: 9, day: 18, text: "버텼던 날의 나에게 하고 싶은 말은?" },
  { month: 9, day: 19, text: "요즘 마음에 드는 색이나 향은?" },
  { month: 9, day: 20, text: "나를 위한 작은 선물을 고른다면?" },
  { month: 9, day: 21, text: "함께 웃었던 가을날이 떠오르나요?" },
  { month: 9, day: 22, text: "흔들릴 때 붙잡아 준 말은?" },
  { month: 9, day: 23, text: "가을비 소리를 들으며 생각한 것은?" },
  { month: 9, day: 24, text: "그날로 돌아가고 싶은 이유는?" },
  { month: 9, day: 25, text: "올해 가을에 꼭 해보고 싶은 것은?" },
  { month: 9, day: 26, text: "따뜻한 한 끼가 위로가 된 적은?" },
  { month: 9, day: 27, text: "9월에 마음에 새긴 장면은?" },
  { month: 9, day: 28, text: "내려놓으면 숨이 트일 것은?" },
  { month: 9, day: 29, text: "가을밤 창밖을 보며 느낀 감정은?" },
  { month: 9, day: 30, text: "9월을 한 문장으로 남긴다면?" },
] as const;
