/** 9월 — 30일 (가을) */
export const MONTH_9_SEEDS = [
  { month: 9, day: 1, text: "일이나 공부에서 보람을 느낀 순간이 있나요? 그 순간을 이야기해주세요", tags: ["experience","growth"] },
  { month: 9, day: 2, text: "지금 하는 일에서 좋아하는 점이 있나요? 그 점을 이야기해주세요", tags: ["daily","experience"] },
  { month: 9, day: 3, text: "퇴근이나 하교 후 기분은 어떤가요? 그 기분을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 9, day: 4, text: "동료나 팀원과의 관계는 어떤가요? 그 관계를 이야기해주세요", tags: ["relationship","experience"] },
  { month: 9, day: 5, text: "업무나 학업 스트레스를 어떻게 풀나요? 그 방법을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 9, day: 6, text: "바꾸고 싶은 업무나 학습 환경이 있나요? 그 이유를 이야기해주세요", tags: ["growth","future"] },
  { month: 9, day: 7, text: "일과 삶의 균형, 지금은 어떤가요? 그 균형에 대해 이야기해주세요", tags: ["daily","reflection"] },
  { month: 9, day: 8, text: "혼자 있을 때 하는 일 중 좋아하는 것이 있나요? 그것을 이야기해주세요", tags: ["experience","self"] },
  { month: 9, day: 9, text: "작은 성취지만 뿌듯했던 일이 있나요? 그 일을 이야기해주세요", tags: ["growth","experience"] },
  { month: 9, day: 10, text: "남들은 모르지만 나만 아는 잘한 일이 있나요? 그 일을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 9, day: 11, text: "포기하지 않아서 다행인 일이 있나요? 그 일을 이야기해주세요", tags: ["growth","hope"] },
  { month: 9, day: 12, text: "만약 다른 직업을 가진다면 어떤 일을 하고 싶나요? 그 마음을 이야기해주세요", tags: ["future","reflection"] },
  { month: 9, day: 13, text: "취미에 쓰는 시간이 충분한가요? 그 시간에 대해 이야기해주세요", tags: ["growth","experience"] },
  { month: 9, day: 14, text: "타인과 비교하며 힘들었던 적이 있나요? 그 경험을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 9, day: 15, text: "실패했지만 다시 일어섰던 경험이 있나요? 그 경험을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 9, day: 16, text: "어떤 불안을 가지고 있나요? 그 불안에 대해 이야기해주세요", tags: ["experience","emotion"] },
  { month: 9, day: 17, text: "걱정을 줄이기 위해 하는 일이 있나요? 그 일을 이야기해주세요", tags: ["growth","daily"] },
  { month: 9, day: 18, text: "결정을 미루는 편인가요? 그 이유를 이야기해주세요", tags: ["experience","reflection"] },
  { month: 9, day: 19, text: "어려운 선택을 앞두고 있나요? 그 선택에 대해 이야기해주세요", tags: ["experience","hope"] },
  { month: 9, day: 20, text: "선택의 순간에 가장 중요하게 여기는 것은 무엇인가요? 그 기준을 이야기해주세요", tags: ["growth","reflection"] },
  { month: 9, day: 21, text: "내린 선택 하나를 떠올릴 수 있나요? 그 선택에 대해 이야기해주세요", tags: ["experience","memory"] },
  { month: 9, day: 22, text: "스스로에게 너무 엄격했던 적이 있나요? 그 경험을 이야기해주세요", tags: ["growth","self"] },
  { month: 9, day: 23, text: "통제할 수 없는 것을 놓아본 적이 있나요? 그 경험을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 9, day: 24, text: "중요한 결정을 내릴 때 무엇을 더 많이 믿는 편인가요? 최근의 선택을 이야기해주세요", tags: ["growth","future"] },
  { month: 9, day: 25, text: "뉴스나 SNS를 보며 마음이 무거워진 적이 있나요? 그때의 마음을 이야기해주세요", tags: ["experience","emotion"] },
  { month: 9, day: 26, text: "다시 일어설 수 있다고 믿나요? 그 믿음에 대해 이야기해주세요", tags: ["growth","hope"] },
  { month: 9, day: 27, text: "가장 처음 떠오르는 후회되는 일이 있나요? 그 일을 이야기해주세요", tags: ["experience","reflection"] },
  { month: 9, day: 28, text: "오래 하고 싶은 취미가 있나요? 그 취미에 대해 이야기해주세요", tags: ["growth","experience"] },
  { month: 9, day: 29, text: "당신의 강점은 무엇인가요? 그 강점이 빛났던 순간을 이야기해주세요", tags: ["experience","self"] },
  { month: 9, day: 30, text: "실패가 두려워서 멈춘 적이 있나요? 그 경험을 이야기해주세요", tags: ["growth","reflection"] },
] as const;
