/** 10월 — 31일 */
export const MONTH_10_SEEDS = [
  { month: 10, day: 1, text: "깊어가는 가을, 마음의 색은?" },
  { month: 10, day: 2, text: "단풍이나 낙엽을 보며 느낀 것은?" },
  { month: 10, day: 3, text: "그리운 음식이나 향이 있다면?" },
  { month: 10, day: 4, text: "마음이 가벼워진 계기는?" },
  { month: 10, day: 5, text: "어릴 적 10월의 기억이 있다면?" },
  { month: 10, day: 6, text: "웃음이 새어 나온 순간은?" },
  { month: 10, day: 7, text: "예전 10월이 그리워진 이유는?" },
  { month: 10, day: 8, text: "가을 햇살 아래 느낀 평화는?" },
  { month: 10, day: 9, text: "지키고 싶은 소소한 일상은?" },
  { month: 10, day: 10, text: "누군가와 함께한 가을날이 떠오르나요?" },
  { month: 10, day: 11, text: "모르는 사람의 친절이 남긴 흔적은?" },
  { month: 10, day: 12, text: "여유를 느낀 하루의 시간대는?" },
  { month: 10, day: 13, text: "소중한 사람과의 장면이 떠오르나요?" },
  { month: 10, day: 14, text: "기다리고 있는 만남이 있나요?" },
  { month: 10, day: 15, text: "단풍처럼 마음에 남은 사람은?" },
  { month: 10, day: 16, text: "가을밤 공기, 어떤 감정을 불러왔나요?" },
  { month: 10, day: 17, text: "한마디가 방향을 바꾼 적이 있나요?" },
  { month: 10, day: 18, text: "최근 눈물 나도록 감동받은 것은?" },
  { month: 10, day: 19, text: "어제의 나에게 남기고 싶은 말은?" },
  { month: 10, day: 20, text: "지금 가고 싶은 곳은 어디인가요?" },
  { month: 10, day: 21, text: "오늘의 기쁨을 나누고 싶은 사람은?" },
  { month: 10, day: 22, text: "가을밤, 다시 살고 싶은 순간은?" },
  { month: 10, day: 23, text: "스스로를 칭찬하고 싶은 행동은?" },
  { month: 10, day: 24, text: "가을날 사진 속 나의 표정은 어땠나요?" },
  { month: 10, day: 25, text: "요즘 손이 자주 가는 취미는?" },
  { month: 10, day: 26, text: "올해 가을에 처음 깨달은 것은?" },
  { month: 10, day: 27, text: "10월 하늘, 어떤 색이 남았나요?" },
  { month: 10, day: 28, text: "낙엽 밟으며 웃었던 순간은?" },
  { month: 10, day: 29, text: "가을 끝, 내려놓고 싶은 마음은?" },
  { month: 10, day: 30, text: "10월을 떠나내며 남기고 싶은 한마디는?" },
  { month: 10, day: 31, text: "가을의 끝, 마음에 남는 색은?" },
] as const;
