/** 10월 — 31일 (가을) */
export const MONTH_10_SEEDS = [
  { month: 10, day: 1, text: "당연하다고 여겼지만 사실 고마운 것이 있나요? 그것을 이야기해주세요", tags: ["reflection","gratitude"] },
  { month: 10, day: 2, text: "스스로에게 고마운 점이 있나요? 그 점을 이야기해주세요", tags: ["gratitude","self"] },
  { month: 10, day: 3, text: "요즘 세상에서 고마운 존재가 있나요? 그 존재를 이야기해주세요", tags: ["gratitude","daily"] },
  { month: 10, day: 4, text: "말하지 못한 고마움이 있나요? 그 고마움을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 10, day: 5, text: "과거의 나에게 해주고 싶은 말이 있나요? 그 말을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 10, day: 6, text: "과거의 나보다 나아졌다고 느끼나요? 그 변화를 이야기해주세요", tags: ["reflection","self"] },
  { month: 10, day: 7, text: "감사했던 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["gratitude","experience"] },
  { month: 10, day: 8, text: "내일은 조금 더 나아질 거라고 믿나요? 그 믿음을 이야기해주세요", tags: ["reflection","hope"] },
  { month: 10, day: 9, text: "지금 가진 것 중 가장 소중한 것이 있나요? 그것을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 10, day: 10, text: "듣고 싶은 말이 있다면 무엇인가요? 그 말을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 10, day: 11, text: "내가 결정한 선택 중 가장 잘한 것은 무엇이었나요? 그 순간을 이야기해주세요", tags: ["reflection","experience"] },
  { month: 10, day: 12, text: "마음이 복잡할 때 글이나 말로 풀어 본 적이 있나요? 그때의 순간을 이야기해주세요", tags: ["reflection","emotion"] },
  { month: 10, day: 13, text: "작은 빛 같은 순간을 기억하나요? 그 순간을 이야기해주세요", tags: ["gratitude","memory"] },
  { month: 10, day: 14, text: "인생에서 가장 중요하게 여기는 우선순위 세 가지가 있다면 무엇인가요? 이야기해주세요", tags: ["reflection","self"] },
  { month: 10, day: 15, text: "혼자만의 작은 의식이 있나요? 그 의식을 이야기해주세요", tags: ["daily","self"] },
  { month: 10, day: 16, text: "영원히 기억하고 싶은 순간이 있나요? 그 순간을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 10, day: 17, text: "지금도 괜찮다고 스스로에게 말할 수 있나요? 그 마음을 이야기해주세요", tags: ["reflection","hope"] },
  { month: 10, day: 18, text: "힘들 때 읽거나 듣는 위로가 있나요? 그 위로를 이야기해주세요", tags: ["hope","experience"] },
  { month: 10, day: 19, text: "미래의 나에게 물어보고 싶은 것이 있나요? 그 질문을 이야기해주세요", tags: ["reflection","future"] },
  { month: 10, day: 20, text: "당신을 지탱해 준 말 한마디가 있나요? 그 말을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 10, day: 21, text: "나에게 자유란 어떤 의미인가요? 그 의미를 이야기해주세요", tags: ["reflection","self"] },
  { month: 10, day: 22, text: "소소하지만 확실한 행복 한 가지를 떠올릴 수 있나요? 그 순간을 이야기해주세요", tags: ["emotion","hope"] },
  { month: 10, day: 23, text: "어릴 적 상상했던 세계가 있나요? 그 세계를 이야기해주세요", tags: ["reflection","memory"] },
  { month: 10, day: 24, text: "잠들기 전 머릿속을 비우는 방법이 있나요? 그 방법을 이야기해주세요", tags: ["reflection","daily"] },
  { month: 10, day: 25, text: "희망을 잃지 않으려고 하는 방법이 있나요? 그 방법을 이야기해주세요", tags: ["hope","self"] },
  { month: 10, day: 26, text: "처음으로 괜찮다고 느꼈던 순간은 언제였나요? 그 순간을 이야기해주세요", tags: ["reflection","experience"] },
  { month: 10, day: 27, text: "스스로에게 잘했다고 말해 주고 싶은 일이 있나요? 그 일을 이야기해주세요", tags: ["growth","self"] },
  { month: 10, day: 28, text: "어릴 적 방을 떠올리면 어떤 장면이 보이나요? 그 기억을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 10, day: 29, text: "내가 힘들 때 어떤 말과 행동이 가장 위로가 되나요? 그것을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 10, day: 30, text: "세상에 믿고 싶은 것이 있나요? 그것을 이야기해주세요", tags: ["reflection","hope"] },
  { month: 10, day: 31, text: "편지를 써 본 적이나 받은 적이 있나요? 그 경험을 이야기해주세요", tags: ["gratitude","experience"] },
] as const;
