/** 11월 — 30일 (감사·회고) */
export const MONTH_11_SEEDS = [
  { month: 11, day: 1, text: "올해를 돌아보며 고마웠던 것이 있나요? 그것을 이야기해주세요", tags: ["gratitude","memory"] },
  { month: 11, day: 2, text: "스스로를 용서하고 싶은 일이 있나요? 그 일을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 11, day: 3, text: "후회가 남지만 그래도 괜찮아진 일이 있나요? 그 일을 이야기해주세요", tags: ["reflection","hope"] },
  { month: 11, day: 4, text: "지나간 일을 붙잡고 있진 않나요? 그 마음을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 11, day: 5, text: "미안함이 남아 있는 관계가 있나요? 그 마음을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 11, day: 6, text: "과거의 실수에서 배운 것이 있나요? 그 배움을 이야기해주세요", tags: ["reflection","growth"] },
  { month: 11, day: 7, text: "용서받고 싶은 마음이 있나요? 그 마음을 이야기해주세요", tags: ["hope","reflection"] },
  { month: 11, day: 8, text: "그리움이 스쳐 지나갔던 순간이 있나요? 그 순간을 이야기해주세요", tags: ["emotion","relationship"] },
  { month: 11, day: 9, text: "집이 편안하다고 느끼나요? 그 편안함에 대해 이야기해주세요", tags: ["place","emotion"] },
  { month: 11, day: 10, text: "정리하고 싶어진 것이 있나요? 그것을 이야기해주세요", tags: ["reflection","self"] },
  { month: 11, day: 11, text: "고마움을 전하고 싶은 사람이 있나요? 그 마음을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 11, day: 12, text: "조용히 혼자 있을 때 편안한가요? 그 느낌을 이야기해주세요", tags: ["memory","emotion"] },
  { month: 11, day: 13, text: "아직 풀지 못한 마음이 있나요? 그 마음을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 11, day: 14, text: "집에 돌아오면 기분이 어떻게 달라지나요? 그 변화를 이야기해주세요", tags: ["place","emotion"] },
  { month: 11, day: 15, text: "누군가의 하루를 대신 살아본다면 누구인가요? 그 마음을 이야기해주세요", tags: ["memory","relationship"] },
  { month: 11, day: 16, text: "거짓말을 해야 했던 순간이 있나요? 그때의 마음을 이야기해주세요", tags: ["reflection","experience"] },
  { month: 11, day: 17, text: "좋아하는 자신의 모습 한 가지가 있나요? 그 모습을 이야기해주세요", tags: ["gratitude","self"] },
  { month: 11, day: 18, text: "바꾸고 싶은 습관이 있나요? 그 습관에 대해 이야기해주세요", tags: ["reflection","self"] },
  { month: 11, day: 19, text: "당신에게 나다움이란 무엇인가요? 그 나다움을 이야기해주세요", tags: ["memory","hope"] },
  { month: 11, day: 20, text: "말 대신 행동으로 전한 적이 있나요? 그 경험을 이야기해주세요", tags: ["gratitude","relationship"] },
  { month: 11, day: 21, text: "진심을 전했을 때 후회한 적이 있나요? 그 경험을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 11, day: 22, text: "혼자인 지금, 어떤가요? 그 마음을 이야기해주세요", tags: ["memory","emotion"] },
  { month: 11, day: 23, text: "혼자 있는 시간이 나에게 주는 것이 있나요? 그 경험을 이야기해주세요", tags: ["self","daily"] },
  { month: 11, day: 24, text: "최근에 내린 결정 중 후회 없는 것이 있나요? 그 결정을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 11, day: 25, text: "마음속에만 두었던 이야기가 있나요? 지금 꺼내 본다면 무엇인가요? 이야기해주세요", tags: ["memory","relationship"] },
  { month: 11, day: 26, text: "나만의 안식처처럼 느껴지는 공간이 있나요? 그 공간을 이야기해주세요", tags: ["place","emotion"] },
  { month: 11, day: 27, text: "결정 후 후회한 적이 있나요? 그 경험을 이야기해주세요", tags: ["reflection","memory"] },
  { month: 11, day: 28, text: "나를 표현하는 방법은 무엇인가요? 그 방법을 이야기해주세요", tags: ["memory","self"] },
  { month: 11, day: 29, text: "잘 먹고 있다고 스스로에게 말해 줄 수 있나요? 그 마음을 이야기해주세요", tags: ["hope","self"] },
  { month: 11, day: 30, text: "미래에 대한 불안을 누구에게 털어놓나요? 그 경험을 이야기해주세요", tags: ["reflection","future"] },
] as const;
