/** 11월 — 30일 */
export const MONTH_11_SEEDS = [
  { month: 11, day: 1, text: "늦가을, 마음이 무거워질 때 위로는?" },
  { month: 11, day: 2, text: "차가운 바람 속에서도 따뜻했던 것은?" },
  { month: 11, day: 3, text: "힘들 때 기억나는 말이나 행동은?" },
  { month: 11, day: 4, text: "최근 마음을 덜어준 사람은?" },
  { month: 11, day: 5, text: "어릴 적 11월의 기억이 있다면?" },
  { month: 11, day: 6, text: "예전 11월이 그리워진 이유는?" },
  { month: 11, day: 7, text: "지금의 나를 만든 한 번의 경험은?" },
  { month: 11, day: 8, text: "몸이 쉬라고 신호를 보낸 때는?" },
  { month: 11, day: 9, text: "따뜻한 음료를 마시며 생각한 것은?" },
  { month: 11, day: 10, text: "소중한 관계의 가장 큰 이유는?" },
  { month: 11, day: 11, text: "함께 웃었던 늦가을이 떠오르나요?" },
  { month: 11, day: 12, text: "11월에 떠올린 작은 모험은?" },
  { month: 11, day: 13, text: "쓸쓸한 날, 마음이 환해진 계기는?" },
  { month: 11, day: 14, text: "미래를 그리며 설렌 적이 있나요?" },
  { month: 11, day: 15, text: "늦가을, 고마움을 느낀 사람은?" },
  { month: 11, day: 16, text: "늦가을 산책에서 본 풍경은?" },
  { month: 11, day: 17, text: "버텼던 나에게 건네고 싶은 말은?" },
  { month: 11, day: 18, text: "11월에 몸과 마음을 돌본 방법은?" },
  { month: 11, day: 19, text: "다가올 나에게 남기고 싶은 말은?" },
  { month: 11, day: 20, text: "앞으로의 일을 떠올리며 설렌 적이 있나요?" },
  { month: 11, day: 21, text: "연락하고 싶은 사람이 떠오르나요?" },
  { month: 11, day: 22, text: "쓸쓸한 날, 마음을 데운 것은?" },
  { month: 11, day: 23, text: "차가운 바람 속, 다시 살고 싶은 순간은?" },
  { month: 11, day: 24, text: "11월에 스스로를 뿌듯하게 만든 순간은?" },
  { month: 11, day: 25, text: "11월에 가장 기억에 남는 맛은?" },
  { month: 11, day: 26, text: "창밖 풍경이 전한 메시지는?" },
  { month: 11, day: 27, text: "올해 겨울을 앞두며 느낀 것은?" },
  { month: 11, day: 28, text: "겨울 앞, 내려놓고 싶은 마음은?" },
  { month: 11, day: 29, text: "11월을 한 문장으로 남긴다면?" },
  { month: 11, day: 30, text: "늦가을의 끝, 마음에 남는 풍경은?" },
] as const;
