/** 12월 — 31일 (마무리·Echo) */
export const MONTH_12_SEEDS = [
  { month: 12, day: 1, text: "올해를 한 단어로 표현한다면 무엇인가요? 그 단어를 고른 이유를 이야기해주세요", tags: ["echo","reflection"] },
  { month: 12, day: 2, text: "올해 가장 기억에 남는 하루가 있었나요? 그 하루를 이야기해주세요", tags: ["echo","memory"] },
  { month: 12, day: 3, text: "내년 이맘때쯤 어떤 이야기를 하고 싶나요? 그 이야기를 해주세요", tags: ["future","hope"] },
  { month: 12, day: 4, text: "올해 고마웠던 사람 한 명을 떠올릴 수 있나요? 그 이유를 이야기해주세요", tags: ["echo","gratitude"] },
  { month: 12, day: 5, text: "1년 뒤의 나에게 하고 싶은 이야기가 있나요? 그 이야기를 해주세요", tags: ["future","self"] },
  { month: 12, day: 6, text: "올해 성장했다고 느낀 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["echo","growth"] },
  { month: 12, day: 7, text: "타임캡슐에 오늘의 마음을 담는다면 어떤 이야기를 남기고 싶나요? 이야기해주세요", tags: ["timecapsule","emotion"] },
  { month: 12, day: 8, text: "올해 처음 해본 일 중 기억에 남는 것이 있나요? 그 경험을 이야기해주세요", tags: ["echo","experience"] },
  { month: 12, day: 9, text: "미래에 대한 희망을 한 문장으로 말한다면 무엇인가요? 그 문장을 이야기해주세요", tags: ["future","hope"] },
  { month: 12, day: 10, text: "올해의 나를 돌아보며 가장 많이 느낀 감정은 무엇인가요? 그 감정을 이야기해주세요", tags: ["echo","reflection"] },
  { month: 12, day: 11, text: "훗날의 나에게 보내고 싶은 편지가 있다면 무엇을 전하고 싶나요? 이야기해주세요", tags: ["timecapsule","future"] },
  { month: 12, day: 12, text: "올해 관계에서 배운 것이 있나요? 그 배움을 이야기해주세요", tags: ["echo","relationship"] },
  { month: 12, day: 13, text: "1년 뒤의 나에게 묻고 싶은 질문이 있다면 무엇인가요? 그 질문을 이야기해주세요", tags: ["future","reflection"] },
  { month: 12, day: 14, text: "올해 가장 조용했던 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["echo","memory"] },
  { month: 12, day: 15, text: "1년 뒤의 나에게도 전하고 싶은 말이 있나요? 이야기해주세요", tags: ["timecapsule","hope"] },
  { month: 12, day: 16, text: "올해 당연하다고 여겼지만 고마웠던 것이 있나요? 그것을 이야기해주세요", tags: ["echo","gratitude"] },
  { month: 12, day: 17, text: "지금보다 1년 뒤의 나에게 바라는 모습이 있다면 어떤 모습인가요? 그 모습을 이야기해주세요", tags: ["future","self"] },
  { month: 12, day: 18, text: "올해 가장 용기를 냈던 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["echo","experience"] },
  { month: 12, day: 19, text: "오늘의 이야기를 서랍에 남긴다면 어떤 한 문장으로 적고 싶나요? 이야기해주세요", tags: ["timecapsule","reflection"] },
  { month: 12, day: 20, text: "올해 품었던 희망 중 아직 남아 있는 것이 있나요? 그 희망을 이야기해주세요", tags: ["echo","hope"] },
  { month: 12, day: 21, text: "지금의 선택이 1년 뒤의 나를 바꿀 수 있다고 믿나요? 그 마음을 이야기해주세요", tags: ["future","reflection"] },
  { month: 12, day: 22, text: "올해 가장 따뜻했던 순간이 있었나요? 그 순간을 이야기해주세요", tags: ["echo","memory"] },
  { month: 12, day: 23, text: "1년 뒤 같은 질문을 받는다면 지금과 같은 답을 할 것 같나요? 그 마음을 이야기해주세요", tags: ["timecapsule","echo"] },
  { month: 12, day: 24, text: "작은 변화 하나가 1년 뒤의 나를 바꿀 수 있다고 믿나요? 그 변화를 이야기해주세요", tags: ["future","hope"] },
  { month: 12, day: 25, text: "올해의 나에게 스스로에게 남기고 싶은 말이 있나요? 그 말을 이야기해주세요", tags: ["echo","self"] },
  { month: 12, day: 26, text: "지금 이 질문에 답하며 떠오른 마음, 그대로 이야기해주세요", tags: ["timecapsule","emotion"] },
  { month: 12, day: 27, text: "누군가에게 이 이야기를 공유하고 싶은 순간이 있나요? 그 마음을 이야기해주세요", tags: ["echo","relationship"] },
  { month: 12, day: 28, text: "당신의 인생에서 꼭 지키고 싶은 일이 있다면 무엇인가요? 그것을 이야기해주세요", tags: ["future","reflection"] },
  { month: 12, day: 29, text: "올해의 마지막 주, 마음에 남기고 싶은 이야기가 있나요? 자유롭게 이야기해주세요", tags: ["timecapsule","memory"] },
  { month: 12, day: 30, text: "한 해를 마무리하며 고마운 마음을 전하고 싶은 사람이 있나요? 그 마음을 이야기해주세요", tags: ["echo","gratitude"] },
  { month: 12, day: 31, text: "새해의 나에게 건네고 싶은 말 한마디가 있다면 무엇인가요? 그 말을 이야기해주세요", tags: ["timecapsule","future"] },
] as const;
