/** 12월 — 31일 */
export const MONTH_12_SEEDS = [
  { month: 12, day: 1, text: "한 해의 마지막 달, 마음은 어디에 있나요?" },
  { month: 12, day: 2, text: "차가운 계절, 나를 따뜻하게 한 것은?" },
  { month: 12, day: 3, text: "그리운 장소가 있다면 어디인가요?" },
  { month: 12, day: 4, text: "올해 가장 기억에 남는 하루는?" },
  { month: 12, day: 5, text: "어릴 적 12월의 기억이 있다면?" },
  { month: 12, day: 6, text: "예전 12월이 그리워진 이유는?" },
  { month: 12, day: 7, text: "올해 후회 없이 한 선택은?" },
  { month: 12, day: 8, text: "12월에 고마움을 느낀 일은?" },
  { month: 12, day: 9, text: "12월에 여유를 느낀 시간대는?" },
  { month: 12, day: 10, text: "함께 웃었던 겨울날이 떠오르나요?" },
  { month: 12, day: 11, text: "눈이나 비 오는 날, 떠올린 것은?" },
  { month: 12, day: 12, text: "한 해의 끝, 고마움을 느낀 사람은?" },
  { month: 12, day: 13, text: "한 해를 돌아보며 배운 것은?" },
  { month: 12, day: 14, text: "12월에 나에게 주고 싶은 선물은?" },
  { month: 12, day: 15, text: "12월에 지키고 싶은 일상은?" },
  { month: 12, day: 16, text: "겨울밤 불빛 아래 느낀 감정은?" },
  { month: 12, day: 17, text: "12월의 어제, 나에게 고마웠던 점은?" },
  { month: 12, day: 18, text: "나를 성장시킨 올해의 경험은?" },
  { month: 12, day: 19, text: "요즘 자주 듣는 노래의 제목은?" },
  { month: 12, day: 20, text: "12월에 듣고 싶었던 말이 있었나요?" },
  { month: 12, day: 21, text: "12월의 기쁨을 나누고 싶은 사람은?" },
  { month: 12, day: 22, text: "겨울밤, 다시 살고 싶은 순간은?" },
  { month: 12, day: 23, text: "12월에 스스로를 칭찬하고 싶은 행동은?" },
  { month: 12, day: 24, text: "오늘 밤, 마음에 남기고 싶은 것은?" },
  { month: 12, day: 25, text: "따뜻한 날, 누구와 함께였나요?" },
  { month: 12, day: 26, text: "한 해를 닫으며 내려놓고 싶은 것은?" },
  { month: 12, day: 27, text: "내년에 꼭 해보고 싶은 것은?" },
  { month: 12, day: 28, text: "12월 중 가장 행복했던 날은?" },
  { month: 12, day: 29, text: "한 해를 마무리하며 느낀 것은?" },
  { month: 12, day: 30, text: "12월을 떠나내며 남기고 싶은 한마디는?" },
  { month: 12, day: 31, text: "올해의 나에게 건네고 싶은 말은?" },
] as const;
